config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :assign_logs
  resources :actions
  resources :recommendations
  resources :evaluations
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)

    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully created.' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:name, :award_type, :award_number, :cor, :contact, :evaluation_date, :activity_partner)
    end
end

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evaluations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Award type</th>
      <th>Award number</th>
      <th>Cor</th>
      <th>Contact</th>
      <th>Evaluation date</th>
      <th>Activity partner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
        <td><%= evaluation.name %></td>
        <td><%= evaluation.award_type %></td>
        <td><%= evaluation.award_number %></td>
        <td><%= evaluation.cor %></td>
        <td><%= evaluation.contact %></td>
        <td><%= evaluation.evaluation_date %></td>
        <td><%= evaluation.activity_partner %></td>
        <td><%= link_to 'Show', evaluation %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        <td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluation', new_evaluation_path %>

app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Back', evaluations_path %>

app/views/evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @evaluation.name %>
</p>

<p>
  <strong>Award type:</strong>
  <%= @evaluation.award_type %>
</p>

<p>
  <strong>Award number:</strong>
  <%= @evaluation.award_number %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @evaluation.cor %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @evaluation.contact %>
</p>

<p>
  <strong>Evaluation date:</strong>
  <%= @evaluation.evaluation_date %>
</p>

<p>
  <strong>Activity partner:</strong>
  <%= @evaluation.activity_partner %>
</p>

<%= link_to 'Edit', edit_evaluation_path(@evaluation) %> |
<%= link_to 'Back', evaluations_path %>