config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :assign_logs
  resources :actions
  resources :recommendations
  resources :evaluations
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
  end

  # GET /recommendations/1/edit
  def edit
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: 'Recommendation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:description, :status, :mission_response, :comments)
    end
end

app/views/recommendations/edit.html.erb
<h1>Editing Recommendation</h1>

<%= render 'form', recommendation: @recommendation %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/recommendations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recommendations</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Status</th>
      <th>Mission response</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommendations.each do |recommendation| %>
      <tr>
        <td><%= recommendation.description %></td>
        <td><%= recommendation.status %></td>
        <td><%= recommendation.mission_response %></td>
        <td><%= recommendation.comments %></td>
        <td><%= link_to 'Show', recommendation %></td>
        <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
        <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommendation', new_recommendation_path %>

app/views/recommendations/new.html.erb
<h1>New Recommendation</h1>

<%= render 'form', recommendation: @recommendation %>

<%= link_to 'Back', recommendations_path %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @recommendation.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @recommendation.status %>
</p>

<p>
  <strong>Mission response:</strong>
  <%= @recommendation.mission_response %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @recommendation.comments %>
</p>

<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>