config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :assign_logs
  resources :actions
  resources :recommendations
  resources :evaluations
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/assign_log.rb
class AssignLog < ApplicationRecord
end

app/controllers/assign_logs_controller.rb
class AssignLogsController < ApplicationController
  before_action :set_assign_log, only: [:show, :edit, :update, :destroy]

  # GET /assign_logs
  # GET /assign_logs.json
  def index
    @assign_logs = AssignLog.all
  end

  # GET /assign_logs/1
  # GET /assign_logs/1.json
  def show
  end

  # GET /assign_logs/new
  def new
    @assign_log = AssignLog.new
  end

  # GET /assign_logs/1/edit
  def edit
  end

  # POST /assign_logs
  # POST /assign_logs.json
  def create
    @assign_log = AssignLog.new(assign_log_params)

    respond_to do |format|
      if @assign_log.save
        format.html { redirect_to @assign_log, notice: 'Assign log was successfully created.' }
        format.json { render :show, status: :created, location: @assign_log }
      else
        format.html { render :new }
        format.json { render json: @assign_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assign_logs/1
  # PATCH/PUT /assign_logs/1.json
  def update
    respond_to do |format|
      if @assign_log.update(assign_log_params)
        format.html { redirect_to @assign_log, notice: 'Assign log was successfully updated.' }
        format.json { render :show, status: :ok, location: @assign_log }
      else
        format.html { render :edit }
        format.json { render json: @assign_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assign_logs/1
  # DELETE /assign_logs/1.json
  def destroy
    @assign_log.destroy
    respond_to do |format|
      format.html { redirect_to assign_logs_url, notice: 'Assign log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assign_log
      @assign_log = AssignLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assign_log_params
      params.require(:assign_log).permit(:user_id, :evaluation_id, :recommendation_id, :action_id)
    end
end

app/views/assign_logs/edit.html.erb
<h1>Editing Assign Log</h1>

<%= render 'form', assign_log: @assign_log %>

<%= link_to 'Show', @assign_log %> |
<%= link_to 'Back', assign_logs_path %>

app/views/assign_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assign Logs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Evaluation</th>
      <th>Recommendation</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assign_logs.each do |assign_log| %>
      <tr>
        <td><%= assign_log.user_id %></td>
        <td><%= assign_log.evaluation_id %></td>
        <td><%= assign_log.recommendation_id %></td>
        <td><%= assign_log.action_id %></td>
        <td><%= link_to 'Show', assign_log %></td>
        <td><%= link_to 'Edit', edit_assign_log_path(assign_log) %></td>
        <td><%= link_to 'Destroy', assign_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assign Log', new_assign_log_path %>

app/views/assign_logs/new.html.erb
<h1>New Assign Log</h1>

<%= render 'form', assign_log: @assign_log %>

<%= link_to 'Back', assign_logs_path %>

app/views/assign_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @assign_log.user_id %>
</p>

<p>
  <strong>Evaluation:</strong>
  <%= @assign_log.evaluation_id %>
</p>

<p>
  <strong>Recommendation:</strong>
  <%= @assign_log.recommendation_id %>
</p>

<p>
  <strong>Action:</strong>
  <%= @assign_log.action_id %>
</p>

<%= link_to 'Edit', edit_assign_log_path(@assign_log) %> |
<%= link_to 'Back', assign_logs_path %>